#!/bin/bash
# musl Configure Script for i286 OS/2 Target
# This script configures musl for compilation with llvm-i286

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
MUSL_DIR="$SCRIPT_DIR/musl"

echo "=== musl Configure for i286 OS/2 Target ==="
echo ""

# Check for required tools
echo "Checking for required tools..."

# Check for clang
if ! command -v clang &> /dev/null; then
    echo "Error: clang not found. Please install LLVM/Clang."
    exit 1
fi
echo "  clang: $(clang --version | head -1)"

# Check for llvm-i286
LLVM_I286="$SCRIPT_DIR/build/llvm-i286"
if [ ! -x "$LLVM_I286" ]; then
    echo "Error: llvm-i286 not found at $LLVM_I286"
    echo "Please build llvm-i286 first: cd build && cmake .. && make"
    exit 1
fi
echo "  llvm-i286: $LLVM_I286"

# Check for nasm
if ! command -v nasm &> /dev/null; then
    echo "Error: nasm not found. Please install NASM."
    exit 1
fi
echo "  nasm: $(nasm -v)"

# Check for wlink (OpenWatcom)
WATCOM="${WATCOM:-$HOME/ow/open-watcom-v2/rel}"
if [ ! -f "$WATCOM/binl64/wlink" ]; then
    echo "Warning: wlink not found at $WATCOM/binl64/wlink"
    echo "Set WATCOM environment variable to OpenWatcom installation directory"
fi
echo "  wlink: $WATCOM/binl64/wlink"

echo ""

# Create config.mak for i286 target
echo "Creating config.mak for i286 target..."

cat > "$MUSL_DIR/config.mak" << 'EOF'
# musl config.mak for i286 OS/2 target
# Generated by configure_i286.sh

ARCH = i286

# Cross-compilation prefix (empty for native compilation)
CROSS_COMPILE =

# C compiler - clang with i286 target
CC = clang -target i286-unknown-os2

# CFLAGS for freestanding environment
CFLAGS_C99FSE = -std=c99 -ffreestanding -nostdinc

# Additional CFLAGS
CFLAGS_AUTO = -Os -pipe

# No dynamic linking
shared = no
static = yes

# No stack protector (not available in freestanding environment)
CFLAGS_NOSSP = -fno-stack-protector

# No CFI (no assembly preprocessing needed)
ADD_CFI = no

# No wrapper tools
tools =
tool_libs =

# Library paths
prefix = /usr/local/musl-i286
exec_prefix = \$(prefix)
bindir = \$(exec_prefix)/bin
libdir = \$(prefix)/lib
includedir = \$(prefix)/include
syslibdir = /lib

# Source directory
srcdir = .

# No optimization for initial port
optimize = no

# No debug
debug = no

# No warnings
warnings = no

EOF

echo "  Created: $MUSL_DIR/config.mak"
echo ""

# Create wrapper scripts
echo "Creating build wrapper scripts..."

# Create clang wrapper that runs clang -> llvm-i286 -> nasm
cat > "$SCRIPT_DIR/musl_cc.sh" << 'CCSCRIPT'
#!/bin/bash
# musl C compiler wrapper for i286
# Runs: clang -emit-llvm -> llvm-i286 -> nasm

set -e

LLVM_I286="$(dirname "$0")/build/llvm-i286"
NASM_FLAGS="-f obj"

# Extract output file from arguments
OUTPUT=""
INPUT=""
ARGS=()

for arg in "$@"; do
    case "$arg" in
        -o) 
            # Next argument is output file
            read -r OUTPUT
            ;;
        -c)
            # Compile only (don't link)
            ARGS+=("$arg")
            ;;
        *.c)
            INPUT="$arg"
            ;;
        *)
            ARGS+=("$arg")
            ;;
    esac
done

if [ -z "$INPUT" ]; then
    echo "Error: no input file" >&2
    exit 1
fi

# Generate a temporary LLVM IR file
LL_FILE="${INPUT%.c}.ll"
ASM_FILE="${INPUT%.c}.asm"

# Step 1: Compile C to LLVM IR
echo "  [1/3] clang -emit-llvm $INPUT -> $LL_FILE"
clang -target i286-unknown-os2 \
      -std=c99 -ffreestanding -nostdinc \
      -Os -pipe \
      -S -emit-llvm \
      -o "$LL_FILE" \
      "$INPUT"

# Step 2: Lower LLVM IR to NASM assembly
echo "  [2/3] llvm-i286 $LL_FILE -> $ASM_FILE"
"$LLVM_I286" "$LL_FILE" -o "$ASM_FILE"

# Step 3: Assemble NASM to object file
if [ -n "$OUTPUT" ]; then
    echo "  [3/3] nasm $NASM_FLAGS -o $OUTPUT $ASM_FILE"
    nasm $NASM_FLAGS -o "$OUTPUT" "$ASM_FILE"
else
    OBJ_FILE="${INPUT%.c}.o"
    echo "  [3/3] nasm $NASM_FLAGS -o $OBJ_FILE $ASM_FILE"
    nasm $NASM_FLAGS -o "$OBJ_FILE" "$ASM_FILE"
fi

# Clean up temporary files
rm -f "$LL_FILE" "$ASM_FILE"

CCSCRIPT

chmod +x "$SCRIPT_DIR/musl_cc.sh"
echo "  Created: $SCRIPT_DIR/musl_cc.sh"

echo ""
echo "=== Configuration Complete ==="
echo ""
echo "Next steps:"
echo "  1. cd $MUSL_DIR"
echo "  2. make CC=$SCRIPT_DIR/musl_cc.sh"
echo ""
echo "Note: Only static library (libc.a) will be built."
echo "      Dynamic linking is not supported in initial port."
echo ""
