// Emitter Implementation
// Emits 80286 instructions as NASM assembly text

#include "codegen/Emitter.h"

namespace llvm_i286 {
namespace codegen {

struct Emitter::Impl {
    // Implementation details
};

Emitter::Emitter() : impl(std::make_unique<Impl>()) {}

Emitter::~Emitter() = default;

std::string Emitter::emitInstruction(const Instruction286& inst) {
    std::string line = "  " + inst.mnemonic;
    
    if (!inst.operands.empty()) {
        line += " ";
        for (size_t i = 0; i < inst.operands.size(); i++) {
            if (i > 0) line += ", ";
            line += inst.operands[i];
        }
    }
    
    if (!inst.comment.empty()) {
        line += " ; " + inst.comment;
    }
    
    return line;
}

std::string Emitter::emitLoweredInstruction(const LoweredInstruction& lowered) {
    std::string output;
    
    // Emit label if present
    if (!lowered.label.empty()) {
        output += lowered.label + ":\n";
    }
    
    // Emit each instruction
    for (const auto& inst : lowered.instructions) {
        output += emitInstruction(inst) + "\n";
    }
    
    return output;
}

std::string Emitter::emitFunction(const std::vector<LoweredInstruction>& instructions,
                                  const std::string& funcName) {
    std::string output;
    
    output += "global " + funcName + "\n";
    output += funcName + ":\n";
    
    // Emit prologue
    output += "  push bp\n";
    output += "  mov bp, sp\n";
    output += "  push bx\n";
    output += "  push si\n";
    output += "  push di\n";
    
    // Emit instructions (RetTerm from instruction selector includes epilogue and ret)
    for (const auto& lowered : instructions) {
        // Skip the function label since we already emitted it
        if (lowered.label == funcName) continue;
        output += emitLoweredInstruction(lowered);
    }
    
    return output;
}

std::string Emitter::emitModule(const std::string& moduleName,
                                const std::string& codeSegment,
                                const std::string& dataSegment,
                                const std::string& bssSegment,
                                const std::string& entryFuncName,
                                const std::vector<std::string>& externFuncs) {
    std::string output;
    
    output += "; Generated by llvm-i286 code generator\n";
    output += "; Module: " + moduleName + "\n";
    output += "\n\nBITS 16\n\n";
    
    // Constants
    output += "cr\t\tequ 0x0d\n";
    output += "lf\t\tequ 0x0a\n";
    output += "stdin\t\tequ 0\n";
    output += "stdout\t\tequ 1\n\n";
    
    // Group data segments
    output += "group DGROUP _DATA\n\n";
    
    // External OS/2 API calls
    output += "        extern  DOSEXIT\n";
    output += "\t        extern  DOSWRITE\n";
    output += "\t        extern  DOSREAD\n";
    
    // External function declarations
    for (const auto& func : externFuncs) {
        output += "\t        extern  " + func + "\n";
    }
    output += "\n";
    
    // Data segment
    output += "segment _DATA CLASS=DATA\n\n";
    if (!dataSegment.empty()) {
        output += dataSegment;
    }
    // Always add standard data variables
    output += "rlen\t\tdw 0\n";
    output += "wlen\t\tdw 0\n";
    output += "\n";
    
    // Stack segment
    output += "segment\tSTACK stack\n";
    output += "\tresw 2048\t\t\t; 4096 bytes stack\n\n";
    
    // Code segment
    output += "segment _TEXT CLASS=CODE\n\n";
    
    if (!entryFuncName.empty()) {
        // Program with entry function: ..start: calls entry function, then exits
        output += "..start:\n";
        output += "                ;  Program entry point - call " + entryFuncName + "\n";
        output += "                call\t" + entryFuncName + "\n";
        output += "\n";
        
        // Exit code MUST be before entry function so return address points here
        output += "exit:\n";
        output += "\t\tpush    ax              \t; return code\n";
        output += "\t\tpush    0               \t; action code 0 = terminate\n";
        output += "       call\tfar DOSEXIT\n";
        output += "\n";
    } else {
        // No entry function: emit code directly at ..start:
        output += "..start:\n";
        output += "                ;  Program entry point\n";
        output += "                \n";
    }
    
    // User functions
    output += codeSegment;
    
    if (entryFuncName.empty()) {
        // No entry function: exit code after user code
        output += "exit:\n";
        output += "\t\tpush    ax              \t; return code\n";
        output += "\t\tpush    0               \t; action code 0 = terminate\n";
        output += "       call\tfar DOSEXIT\n";
    }
    
    // Runtime routines are provided by the runtime library (runtime.lib)
    // See runtime/ directory for printnum, __mul32, __div32
    
    output += "segment _DATA\n";
    output += "\n";
    output += "segment end\n";
    
    return output;
}

} // namespace codegen
} // namespace llvm_i286
