// Emitter Implementation
// Emits 80286 instructions as NASM assembly text

#include "codegen/Emitter.h"
#include "codegen/NasmSafe.h"
#include <set>
#include <map>

namespace llvm_i286 {
namespace codegen {

struct Emitter::Impl {
    // Implementation details
};

Emitter::Emitter() : impl(std::make_unique<Impl>()) {}

Emitter::~Emitter() = default;

std::string Emitter::emitInstruction(const Instruction286& inst) {
    std::string line = "  " + inst.mnemonic;
    
    if (!inst.operands.empty()) {
        line += " ";
        for (size_t i = 0; i < inst.operands.size(); i++) {
            if (i > 0) line += ", ";
            line += inst.operands[i];
        }
    }
    
    if (!inst.comment.empty()) {
        line += " ; " + inst.comment;
    }
    
    return line;
}

std::string Emitter::emitLoweredInstruction(const LoweredInstruction& lowered) {
    std::string output;
    
    // Emit label if present (mangle if it's a NASM reserved word)
    if (!lowered.label.empty()) {
        output += safeNasmName(lowered.label) + ":\n";
    }
    
    // Emit each instruction
    for (const auto& inst : lowered.instructions) {
        output += emitInstruction(inst) + "\n";
    }
    
    return output;
}

// Pass to handle duplicate labels (workaround for IR parser bug
// that duplicates basic blocks with !llvm.loop metadata)
static std::vector<LoweredInstruction> deduplicateLabels(
    const std::vector<LoweredInstruction>& instructions,
    const std::string& funcName) {
    // First pass: collect label indices (position -> instruction list index)
    // and find which labels are duplicated
    std::map<std::string, std::vector<size_t>> labelIndices;
    for (size_t i = 0; i < instructions.size(); i++) {
        if (!instructions[i].label.empty()) {
            labelIndices[instructions[i].label].push_back(i);
        }
    }
    
    // Find which duplicate label should be discarded.
    // When a label appears twice due to !llvm.loop, the first occurrence
    // is a stray loop header (typically `label: jmp label` - a single
    // self-jump) and the second is the real code. We keep the real code.
    std::set<size_t> skipIndices;
    for (const auto& [label, indices] : labelIndices) {
        if (indices.size() <= 1) continue;
        
        // Skip all occurrences except the LAST one (which has the real code)
        for (size_t k = 0; k + 1 < indices.size(); k++) {
            skipIndices.insert(indices[k]);
        }
    }
    
    // Second pass: emit non-skipped instructions
    std::vector<LoweredInstruction> result;
    for (size_t i = 0; i < instructions.size(); i++) {
        if (skipIndices.count(i)) continue;
        result.push_back(instructions[i]);
    }
    
    return result;
}

std::string Emitter::emitFunction(const std::vector<LoweredInstruction>& instructions,
                                  const std::string& funcName,
                                  int frameSize,
                                  const std::string& linkage) {
    std::string output;

    std::string safeName = safeNasmName(funcName);
    if (linkage != "internal") {
        output += "global " + safeName + "\n";
    }
    output += safeName + ":\n";
    
    // Emit prologue
    output += "  push bp\n";
    output += "  mov bp, sp\n";
    output += "  push bx\n";
    output += "  push si\n";
    output += "  push di\n";
    if (frameSize > 0) {
        output += "  sub sp, " + std::to_string(frameSize) + "\n";
    }
    
    // Deduplicate labels (workaround for IR parser !llvm.loop metadata bug)
    auto deduped = deduplicateLabels(instructions, funcName);
    
    // Emit instructions (RetTerm from instruction selector includes epilogue and ret)
    for (const auto& lowered : deduped) {
        // Skip the function label since we already emitted it
        if (lowered.label == funcName) continue;
        output += emitLoweredInstruction(lowered);
    }
    
    return output;
}

std::string Emitter::emitModule(const std::string& moduleName,
                                const std::string& codeSegment,
                                const std::string& dataSegment,
                                const std::string& bssSegment,
                                const std::string& entryFuncName,
                                const std::vector<std::string>& externFuncs,
                                const std::vector<std::string>& externGlobals,
                                const std::vector<std::string>& definedGlobals) {
    std::string output;
    
    output += "; Generated by llvm-i286 code generator\n";
    output += "; Module: " + moduleName + "\n";
    output += "; Target: Intel 80286 processor\n";
    output += "\n\nBITS 16\n";
    output += "CPU 286\n\n";
    
    // Constants
    output += "cr\t\tequ 0x0d\n";
    output += "lf\t\tequ 0x0a\n";
    output += "__os2_stdin_fd\t\tequ 0\n";
    output += "__os2_stdout_fd\t\tequ 1\n\n";
    
    // Group data segments (DATA + BSS)
    output += "group DGROUP _DATA _BSS\n\n";
    
    // External OS/2 API calls
    output += "        extern  DOSEXIT\n";
    output += "\t        extern  DOSWRITE\n";
    output += "\t        extern  DOSREAD\n";
    output += "\t        extern  DOSOPEN\n";
    output += "\t        extern  DOSCLOSE\n";
    output += "\t        extern  DOSCHGFILEPTR\n";
    output += "\t        extern  DOSGETPID\n";
    output += "\t        extern  DOSGETDATETIME\n";
    output += "\t        extern  DOSSLEEP\n";
    output += "\t        extern  DOSALLOCSEG\n";
    output += "\t        extern  DOSFREESEG\n";
    output += "\t        extern  DOSDELETE\n";
    output += "\t        extern  DOSMKDIR\n";
    output += "\t        extern  DOSRMDIR\n";
    output += "\t        extern  DOSCHDIR\n";
    output += "\t        extern  DOSGETCURRENTDIR\n";
    output += "\t        extern  DOSMOVE\n";
    output += "\t        extern  DOSQFILEINFO\n";
    output += "\t        extern  DOSDUPHANDLE\n";
    output += "\t        extern  DOSMAKEPIPE\n";
    
    // External function declarations
    for (const auto& func : externFuncs) {
        output += "\t        extern  " + func + "\n";
    }
    
    // External global variable declarations
    for (const auto& glob : externGlobals) {
        output += "\t        extern  " + glob + "\n";
    }
    
    // Export defined global variables
    for (const auto& glob : definedGlobals) {
        output += "\t        global  " + glob + "\n";
    }
    output += "\n";
    
    // Data segment (initialized data)
    output += "segment _DATA CLASS=DATA\n\n";
    if (!dataSegment.empty()) {
        output += dataSegment;
    }
    // Always add standard data variables
    output += "rlen\t\tdw 0\n";
    output += "wlen\t\tdw 0\n";
    output += "\n";
    
    // BSS segment (uninitialized data)
    output += "segment _BSS CLASS=BSS\n\n";
    if (!bssSegment.empty()) {
        output += bssSegment;
    }
    output += "\n";
    
    // Stack segment (only for executables with entry point, not library objects)
    if (!entryFuncName.empty()) {
        output += "segment\tSTACK stack\n";
        output += "\tresw 16384\t\t\t; 32768 bytes stack\n\n";
    }

    // Code segment
    output += "segment _TEXT CLASS=CODE\n\n";

    if (!entryFuncName.empty()) {
        // Program with entry function: ..start: calls entry function, then exits
        output += "global ..start\n";
        output += "..start:\n";
        output += "                ;  Program entry point - call " + entryFuncName + "\n";
        output += "                call\tfar " + entryFuncName + "\n";
        output += "\n";
        
        // Exit code MUST be before entry function so return address points here
        output += "exit:\n";
        output += "\t\tpush    ax              \t; return code\n";
        output += "\t\tpush    0               \t; action code 0 = terminate\n";
        output += "       call\tfar DOSEXIT\n";
        output += "\n";
        
        // User functions
        output += codeSegment;
    } else {
        // Helper/library module: emit code only, no start/exit labels
        output += codeSegment;
    }
    
    // End segments
    output += "\n";
    output += "segment end\n";
    
    return output;
}

} // namespace codegen
} // namespace llvm_i286
